// <auto-generated />
namespace Investitee.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Initial : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207271348165_Initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1XS27bMBDdF+gdBK3aRUzHBYIkkBOkdlwYreMgSrOnpZFNlKRUkTLss3XRI/UKHepvyd8gBboxLHI+bx7ncaQ/v347tyvBrSXEioWyb593urYF0gt9Jud9O9HB2aV9e/P+nXPvi5X1Utj1jB16StW3F1pH14QobwGCqo5gXhyqMNAdLxSE+iHpdbuX5LxLAEPYGMuynKdEaiYgfcDHQSg9iHRC+ST0gat8HXfcNKr1QAWoiHrQt8dyCUozDdDJjG3rjjOKQFzgwYmoulcGlV3mw4z3iEyvn9cRpFmLhGFct0K7r7DeWMClxziMINbrJwhyX+bbFtn0I03H0q3mY9KbzPpTz7YeEs7pjONCQLkC24ourl0EBF9AQkw1+I9Ua4jxXMY+pPBzGq6ji+OYuCLdnmGCUClDTTUecgt4A6b5LYC6OsZ+sa0RW4H/DeRcL0qwE7oqVvCvbX2XDNsLnXScQL247Hl/0iEoL2ZRhu+f5nZI1Qjt9sCG1ZQh+40eGc4aXZKZu6Abhti1VfysdTtlo20FUqasxEEydRQqIjtk5ExoFCFHNVnlK5abaWpw5p4uHJHFIJ7aop8SbZkJC6NzaOxiakQ6YrHSQ6rpjJpTG/iiZXaY4CJRk+emSCvaCw/zv+5Vu1s628Vf53CEZQlUXVohlHB23Ru5s+tRTuMtyh+EPBFy1+2xzzsTZN0/Wzk+woa66oE2NtrxHNLgosk5aZHeuBObp7iv/5smZfZSB41+d/LeOzxbWs2YmdgWErVkvmlEd600iI4x6Lg/+YAzrLcymFDJAjz25/AHmDmJWnn9fCpvZaV8/r8OKWbKPziOWjPs+OEilzT2FjT+IOjq4xsMjBPinTYE2lfZcbNg7yjIOrBv+7MQC8iA1obIKydFWxEOqb+TOcgbm1chzBuaBM/QWAUtbMYyCAvasbo6osKkcSoT0NRHku5izQLqadz2QKl0jr9QnqDJvZiBP5bTREeJ"
                       + "vlMKxIyv6/U6ZH/+dBxuYnamaSOotygBYTIsAabyc8K4X+Ietdt7VwjTL7lmEBW+x2C4+bqM9BDKIwPl9A0hAmkU9wwi4hhMTaVLl7Ab22EONxlzhozOYypUHqPyN58IxHwj3PwFtVwCq1UMAAA="; }
        }
    }
}
