// <auto-generated />
namespace Investitee.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Initial1 : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207311223409_Initial1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEANVZ227jNhB9L9B/EPTUFljLSYHFbmDvIo3jwujmgjjd1wUtjW2iFKmSlBH31/rQT+ovdChZN1KyZTdJty+GLQ0P53KGM0P//edfo49PMfM2IBUVfOyfDYa+BzwUEeWrsZ/q5Zt3/scP334zuo7iJ+9zIXdu5HAlV2N/rXVyEQQqXENM1CCmoRRKLPUgFHFAIhGcD4fvgrNhAAjhI5bnjR5SrmkM2Q/8eSV4CIlOCbsRETC1e45v5hmqd0tiUAkJYezP+AaUphpgkAv73iWjBBWZA1seqdXwvdHKL/fDHa9RM7193CaQ7VpsKGRdCuV+gW3jAT66lyIBqbcPsNytpZHvBc11gb2wXFZbY7Y3O+sfz33vNmWMLBg+WBKmwPeStxdzVAh+Bg6SaIjuidYgMS6zCDL1d264SN7288T7YHhuPBEQzoUmGoPsKG6paT4LRedaIl98b0qfIPoEfKXXpbI35Kl4gl9971dOkV64SMsU6sblv/dvOgEVSprk+r3y3tOUR3P6R2n0RKS4tiU8Fswt2dBV5lILEFmvSaiRwA/AMgG1pknO40HBui+V1FSK+EGwGiXLl1/mIpWhUU10STwSuQLd1G4UVGzvlQM7tFNSYXZCKsz+H6nA/4tUuF8LDrdpvAB5yEl9Qn6plAhpZq4V84qBTX2ueeQdpGPukzqh0Q0p0zRhNEQ1xv5wMDhzbN2HXRC5Bbugp7XFD7YLasa6tM9AKNLJ8sNk4TjAiM9BW4KYqpWPHesdS9tBqrTvxCqttSBr1rm4tfOkJtd56Nh53SfopUkNlwTHQBUxboGq9LdPk6bdLZwvI1v1F0HeYBSNSNDRiYxuSJJgXtc6k90Tb563JVdv5sf3HnGOEYSqpQUptS13QuvJCqy3po5EMKVS6QnRZEFMxl9FsSN2mMfFRjad3cgVjCxWmO/1VbX2bNDeP9V9OEWzYjytMwuhJebu0qw1JIzIlubpSrA05l0N2L7V"
                       + "eU9TX58/6Y/QaFDqQI0X/fGqpqMOVj11kUaB5VU7eoETPiuPbD4cxZY9J8cppGltOI7iTidCl8tnFoXcxmXfau5QiB9JoUZhrwM1Xrx+4JvHa3v0a9WlT3Rr4keGz1QPO25dBcn1VK+jo8RrO0OMs0oFTtFtV+F66taHk3tVwn0jmjV3M2X6w7I37GmxXV1dhjhF1hYp+VkWW6uojnYF7vAdgFPxchHfQ/M3NDLVbr5VGuKBERjMf2dXjGJGVAI3hNMlGvsofgNzn4EF+fR7hHJkUCpiX+tlAjXmH5yVDg2zey4B+IbIcE3kdzF5+v4ZBvt/hWcP60smiD5xNPr6puEXiSV/rli2TKaZwkfq0ziNWmFcZV5yun3OabYc3U4eYs0lKixBmmAThmuUlnjsOkX/XlIe0oQw2xq38vQ5cYyLS0j7zQQS4IZ+Hdb22fJA1S23sHLnkC+OnPndkarf1L538s+L1NiPFgIDn1O4c0A+dDHQ515g34adY/Tr3h60jvi9LgssP7Q2jS9yReB2KUi/2v8ZmAaKrioI03txCBvEK2VmfCmKJLA0KkSsY/EGNImQlZdS0yUaia9DUCq7dPxMWIoi13j0RjN+l+ok1WgyxAu2rTvD5NG+/bN7kKbOo7usOKvnMAHVpGgC3PGfUsqiUu9pS03ugDAJuqt9Jpba1MDVtkS6xQrUD2jnvvJceYQ4YQim7vicbKBbt8M+bHpsNKFkJUmsdhjVevP3WmD+X/vwD6KQMeeRGwAA"; }
        }
    }
}
